package com.nyco.reprintreport.util;

public class ReportContants {
	public static final String ORDER = "Order#";
	public static final String ALL_REPRINT_QUERY1 = " AND  ET.STORE_NUMBER = SN.ID AND EMP.BADGE= ET.BADGE_NUMBER AND ET.DATA4 = O.ORDER_NUMBER AND ET.STORE_NUMBER = O.SHIP_NODE AND ET.DATA2 = O.SHIP_GROUP AND ET.DATA5 <>'' AND ET.EVENT_TYPE = 'REPRINT' GROUP BY ET.DATA4, CONVERT(VARCHAR(10),ET.LAST_UPDATE_DATE,110), ET.DATA5,  ET.EVENT_TYPE, SN.NAME, ET.STORE_NUMBER, ET.BADGE_NUMBER, EMP.FIRST_NAME+' '+ EMP.LAST_NAME, CONVERT(VARCHAR(10),O.COMPLETED_DATE,110) order by count(data5) DESC;";
	public static final String CREATE_DATE = "and ET.CREATE_DATE < ";
	public static final String ALL_REPRINT_QUERY = "SELECT ET.DATA4 AS 'Order#', CONVERT(VARCHAR(10),ET.LAST_UPDATE_DATE,110) AS 'Reprint date', CONVERT(VARCHAR(10),O.COMPLETED_DATE,110) AS 'Initial Ship date', ET.DATA5 AS 'Tracking number', COUNT(ET.EVENT_TYPE) AS 'Total# reprints' , ET.STORE_NUMBER AS 'Store#', SN.NAME AS 'Store Name', ET.BADGE_NUMBER AS 'Badge ID', (EMP.FIRST_NAME + ' ' + EMP.LAST_NAME) AS 'Associate Name' FROM WF_EVENT_TRACKING ET, WF_SHIP_NODE SN, WF_ORDER O,WF_EMPLOYEE EMP WHERE  ET.CREATE_DATE >  ";
	
}
